### ISSUE TITLE
Not working on Android 7

### ISSUE THREAD

**Issue by piperh** [thdoan/magnify#42]
Nice, configurable magnifier, easy to install and set up. Jan 2018 works great on desktop and iOS but not functioning on my Android 7. Draws the circle but the image within is not amplified.

**Comment by thdoan** [comment]
I'm on Oreo and this is working fine for me in Chrome:

https://thdoan.github.io/magnify/demo.html

Does the example above work for you?

Note that there is also a mobile version:

https://thdoan.github.io/magnify/demo-mobile.html

**Comment by piperh** [comment]
Now on the same Android 7 device (Huawei Honor 6X) in  ...magnify/demo.html  the lupe is working OK, is pannable and the content shows in the circle. But you cannot scroll the page, any kind of touch on the screen (a tap or a swipe) brings up the lupe.

Then, I don't really see the point of  ...demo-mobile.html   What's the advantage over the default pinch/zoom on a mobile? The actions are quite confusing - a single tap enlarges the image and a swiping motion poduces the lupe. And for me the page is not scrollable.

**Comment by thdoan** [comment]
@piperh It seems like you're not able to scroll because the images take up most of the viewport on the phone, which toggles the lens. You can scroll the demo page by dragging along the left or right edges of the screen. To make it easier to scroll, you can set the image width to be smaller (e.g., width: 80%).

The mobile version was for those who requested to maximize the viewport when zooming. The lens motif works well on the desktop, but not so much on your phone since your finger tends to get in the way.

**Comment by thdoan** [comment]
Autoclose after two weeks of inactivity...
