### ISSUE TITLE
Show zoom div on different position of screen

### ISSUE THREAD

**Issue by kwstasna** [thdoan/magnify#47]
Hello.
Is it possible to show the zoomed div in another position of the body of html?

for example upper right of the screen independently of where the user has began dragging his mouse or finger etc.

And also could it zoom any object or only img? For example any other div or text etc.
Could you point me out any solution? Thanks a lot!

**Comment by thdoan** [comment]
Hi, Magnify is lightweight because it only serves one purpose: provide a magnifying glass zoom experience. If the zoom area is placed somewhere else, then it won't be a magnifying glass effect anymore :-). There are lots of jQuery zoom plugins that will do what you requested -- here's a popular one:

http://www.elevateweb.co.uk/image-zoom/examples

**Comment by kwstasna** [comment]
@thdoan i know its not related but this is only for images.. although what i'm looking for is to zoom on anything inside a div.. event if its a text or something else. Any idea?

**Comment by thdoan** [comment]
Autoclose after two weeks of inactivity...
